name: Build and Deploy to JFrog

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build-deploy:
    runs-on: [self-hosted]

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup JDK 25 for Maven build
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # Build and Deploy to JFrog Artifactory
      - name: Build with Maven & Deploy to JFrog Artifactory
        working-directory: backend
        env:
          MAVEN_USERNAME: ${{ secrets.JFROG_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          mvn clean deploy \
          -Dartifactory.username=$MAVEN_USERNAME \
          -Dartifactory.password=$MAVEN_PASSWORD

